// SPDX-License-Identifier: MIT

pragma solidity 0.7.6;
pragma experimental ABIEncoderV2;

/// @title Transaction types used in pool execTransaction() contract guards
/// @dev Gradually migrate to this enum as we update / add new contract guards
interface ITransactionTypes {
  enum TransactionType {
    NotUsed, // 0
    Approve, // 1
    Exchange, // 2
    AddLiquidity, // 3
    RemoveLiquidity, // 4
    Stake, // 5
    Unstake, // 6
    Claim, // 7
    UnstakeAndClaim, // 8
    AaveDeposit, // 9
    AaveWithdraw, // 10
    AaveSetUserUseReserveAsCollateral, // 11
    AaveBorrow, // 12
    AaveRepay, // 13
    AaveSwapBorrowRateMode, // 14
    AaveRebalanceStableBorrowRate, // 15
    BalancerJoinPool, // 16
    BalancerExitPool, // 17
    EasySwapperDeposit, // 18
    EasySwapperWithdraw, // 19
    UniswapV3Mint, // 20
    UniswapV3IncreaseLiquidity, // 21
    UniswapV3DecreaseLiquidity, // 22
    UniswapV3Burn, // 23
    UniswapV3Collect, // 24
    UniswapV3Multicall, // 25
    LyraOpenPosition, // 26
    LyraClosePosition, // 27
    LyraForceClosePosition, // 28
    KwentaFuturesMarket, // 29
    AddLiquiditySingle, // 30
    RemoveLiquiditySingle, // 31
    MaiTx, // 32
    LyraAddCollateral, // 33
    LyraLiquidatePosition, // 34
    KwentaPerpsV2Market, // 35
    RedeemSynth, // 36
    SynthetixV3CreateAccount, // 37
    SynthetixV3DepositCollateral, // 38
    SynthetixV3WithdrawCollateral, // 39
    SynthetixV3DelegateCollateral, // 40
    SynthetixV3MintUSD, // 41
    SynthetixV3BurnUSD, // 42
    SynthetixV3Multicall, // 43
    XRamCreateVest, // 44
    XRamExitVest, // 45
    SynthetixV3Wrap, // 46
    SynthetixV3Unwrap, // 47
    SynthetixV3BuySynth, // 48
    SynthetixV3SellSynth, // 49
    SonneMint, // 50
    SonneRedeem, // 51
    SonneRedeemUnderlying, // 52
    SonneBorrow, // 53
    SonneRepay, // 54
    SonneComptrollerEnterMarkets, // 55
    SonneComptrollerExitMarket, // 56
    SynthetixV3UndelegateCollateral, // 57
    AaveMigrateToV3, // 58
    FlatMoneyStableDeposit, // 59
    FlatMoneyStableWithdraw, // 60
    FlatMoneyCancelOrder, // 61
    SynthetixV3ClaimReward, // 62
    VelodromeCLStake, // 63
    VelodromeCLUnstake, // 64
    VelodromeCLMint, // 65
    VelodromeCLIncreaseLiquidity, // 66
    VelodromeCLDecreaseLiquidity, // 67
    VelodromeCLBurn, // 68
    VelodromeCLCollect, // 69
    VelodromeCLMulticall, // 70
    FlatMoneyLeverageOpen, // 71
    FlatMoneyLeverageAdjust, // 72
    FlatMoneyLeverageClose, // 73
    SynthetixV3PerpsCreateAccount, // 74
    SynthetixV3PerpsModifyCollateral, // 75
    SynthetixV3PerpsCommitOrder, // 76
    CompoundDeposit, // 77
    CompoundWithdraw, // 78
    CompoundClaimRewards, // 79
    RamsesCLMint, // 80
    RamsesCLIncreaseLiquidity, // 81
    RamsesCLDecreaseLiquidity, // 82
    RamsesCLBurn, // 83
    RamsesCLCollect, // 84
    RamsesCLMulticall, // 85
    RamsesCLGetReward, // 86
    EasySwapperV2Deposit, // 87
    EasySwapperV2InitWithdraw, // 88
    EasySwapperV2CompleteWithdrawSingle, // 89
    EasySwapperV2CompleteWithdrawMultiple, // 90
    SafeTransferERC721, // 91
    PancakeCLMint, // 92
    PancakeCLIncreaseLiquidity, // 93
    PancakeCLDecreaseLiquidity, // 94
    PancakeCLBurn, // 95
    PancakeCLCollect, // 96
    PancakeCLMulticall, // 97
    PancakeCLStake, // 98
    PancakeCLUnstake, // 99
    PancakeCLHarvest, // 100
    GmxMulticall, // 101
    GmxClaimFundingFees, // 102
    GmxClaimCollateral, // 103
    GmxCancelOrder, // 104
    GmxCancelDeposit, // 105
    GmxCancelWithdrawal, // 106
    AcrossDepositV3, // 107
    FluidLendingDeposit, // 108
    FluidLendingWithdraw, // 109
    BuyPendlePT, // 110
    SellPendlePT, // 111
    AaveSetEfficiencyMode // 112
  }
}
