/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IAssetHandlerInterface extends ethers.utils.Interface {
  functions: {
    "addAsset(address,uint16,address)": FunctionFragment;
    "addAssets(tuple[])": FunctionFragment;
    "assetTypes(address)": FunctionFragment;
    "getUSDPrice(address)": FunctionFragment;
    "priceAggregators(address)": FunctionFragment;
    "removeAsset(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addAsset",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addAssets",
    values: [{ asset: string; assetType: BigNumberish; aggregator: string }[]]
  ): string;
  encodeFunctionData(functionFragment: "assetTypes", values: [string]): string;
  encodeFunctionData(functionFragment: "getUSDPrice", values: [string]): string;
  encodeFunctionData(
    functionFragment: "priceAggregators",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "removeAsset", values: [string]): string;

  decodeFunctionResult(functionFragment: "addAsset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addAssets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assetTypes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUSDPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceAggregators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAsset",
    data: BytesLike
  ): Result;

  events: {
    "AddedAsset(address,uint16,address)": EventFragment;
    "RemovedAsset(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddedAsset"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemovedAsset"): EventFragment;
}

export type AddedAssetEvent = TypedEvent<
  [string, number, string] & {
    asset: string;
    assetType: number;
    aggregator: string;
  }
>;

export type RemovedAssetEvent = TypedEvent<[string] & { asset: string }>;

export class IAssetHandler extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAssetHandlerInterface;

  functions: {
    addAsset(
      asset: string,
      assetType: BigNumberish,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addAssets(
      assets: { asset: string; assetType: BigNumberish; aggregator: string }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    assetTypes(asset: string, overrides?: CallOverrides): Promise<[number]>;

    getUSDPrice(asset: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    priceAggregators(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    removeAsset(
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addAsset(
    asset: string,
    assetType: BigNumberish,
    aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addAssets(
    assets: { asset: string; assetType: BigNumberish; aggregator: string }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  assetTypes(asset: string, overrides?: CallOverrides): Promise<number>;

  getUSDPrice(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

  priceAggregators(asset: string, overrides?: CallOverrides): Promise<string>;

  removeAsset(
    asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addAsset(
      asset: string,
      assetType: BigNumberish,
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addAssets(
      assets: { asset: string; assetType: BigNumberish; aggregator: string }[],
      overrides?: CallOverrides
    ): Promise<void>;

    assetTypes(asset: string, overrides?: CallOverrides): Promise<number>;

    getUSDPrice(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    priceAggregators(asset: string, overrides?: CallOverrides): Promise<string>;

    removeAsset(asset: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AddedAsset(address,uint16,address)"(
      asset?: null,
      assetType?: null,
      aggregator?: null
    ): TypedEventFilter<
      [string, number, string],
      { asset: string; assetType: number; aggregator: string }
    >;

    AddedAsset(
      asset?: null,
      assetType?: null,
      aggregator?: null
    ): TypedEventFilter<
      [string, number, string],
      { asset: string; assetType: number; aggregator: string }
    >;

    "RemovedAsset(address)"(
      asset?: null
    ): TypedEventFilter<[string], { asset: string }>;

    RemovedAsset(asset?: null): TypedEventFilter<[string], { asset: string }>;
  };

  estimateGas: {
    addAsset(
      asset: string,
      assetType: BigNumberish,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addAssets(
      assets: { asset: string; assetType: BigNumberish; aggregator: string }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    assetTypes(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    getUSDPrice(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    priceAggregators(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeAsset(
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAsset(
      asset: string,
      assetType: BigNumberish,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addAssets(
      assets: { asset: string; assetType: BigNumberish; aggregator: string }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    assetTypes(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUSDPrice(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    priceAggregators(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeAsset(
      asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
