/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IAssetGuardV24Interface extends ethers.utils.Interface {
  functions: {
    "getBalance(address,address)": FunctionFragment;
    "getDecimals(address)": FunctionFragment;
    "removeAssetCheck(address,address)": FunctionFragment;
    "withdrawProcessing(address,address,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBalance",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "getDecimals", values: [string]): string;
  encodeFunctionData(
    functionFragment: "removeAssetCheck",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProcessing",
    values: [string, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAssetCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProcessing",
    data: BytesLike
  ): Result;

  events: {};
}

export class IAssetGuardV24 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAssetGuardV24Interface;

  functions: {
    getBalance(
      pool: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    getDecimals(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { decimals: BigNumber }>;

    removeAssetCheck(
      poolLogic: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    withdrawProcessing(
      pool: string,
      asset: string,
      withdrawPortion: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        ([string, string] & { to: string; txData: string })[]
      ] & {
        transactions: ([string, string] & { to: string; txData: string })[];
      }
    >;
  };

  getBalance(
    pool: string,
    asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getDecimals(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

  removeAssetCheck(
    poolLogic: string,
    asset: string,
    overrides?: CallOverrides
  ): Promise<void>;

  withdrawProcessing(
    pool: string,
    asset: string,
    withdrawPortion: BigNumberish,
    to: string,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      BigNumber,
      ([string, string] & { to: string; txData: string })[]
    ] & { transactions: ([string, string] & { to: string; txData: string })[] }
  >;

  callStatic: {
    getBalance(
      pool: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDecimals(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    removeAssetCheck(
      poolLogic: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawProcessing(
      pool: string,
      asset: string,
      withdrawPortion: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        ([string, string] & { to: string; txData: string })[]
      ] & {
        transactions: ([string, string] & { to: string; txData: string })[];
      }
    >;
  };

  filters: {};

  estimateGas: {
    getBalance(
      pool: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDecimals(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    removeAssetCheck(
      poolLogic: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawProcessing(
      pool: string,
      asset: string,
      withdrawPortion: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBalance(
      pool: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDecimals(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeAssetCheck(
      poolLogic: string,
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawProcessing(
      pool: string,
      asset: string,
      withdrawPortion: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
