/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IGuardV24Interface extends ethers.utils.Interface {
  functions: {
    "txGuard(address,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "txGuard",
    values: [string, string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "txGuard", data: BytesLike): Result;

  events: {
    "Exchange(address,address,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Exchange"): EventFragment;
}

export type ExchangeEvent = TypedEvent<
  [string, string, BigNumber, string, BigNumber] & {
    fundAddress: string;
    sourceAsset: string;
    sourceAmount: BigNumber;
    dstAsset: string;
    time: BigNumber;
  }
>;

export class IGuardV24 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IGuardV24Interface;

  functions: {
    txGuard(
      poolManagerLogic: string,
      to: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  txGuard(
    poolManagerLogic: string,
    to: string,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    txGuard(
      poolManagerLogic: string,
      to: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {
    "Exchange(address,address,uint256,address,uint256)"(
      fundAddress?: null,
      sourceAsset?: null,
      sourceAmount?: null,
      dstAsset?: null,
      time?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, BigNumber],
      {
        fundAddress: string;
        sourceAsset: string;
        sourceAmount: BigNumber;
        dstAsset: string;
        time: BigNumber;
      }
    >;

    Exchange(
      fundAddress?: null,
      sourceAsset?: null,
      sourceAmount?: null,
      dstAsset?: null,
      time?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, BigNumber],
      {
        fundAddress: string;
        sourceAsset: string;
        sourceAmount: BigNumber;
        dstAsset: string;
        time: BigNumber;
      }
    >;
  };

  estimateGas: {
    txGuard(
      poolManagerLogic: string,
      to: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    txGuard(
      poolManagerLogic: string,
      to: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
