/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IHasAssetInfoInterface extends ethers.utils.Interface {
  functions: {
    "getAssetPrice(address)": FunctionFragment;
    "getAssetType(address)": FunctionFragment;
    "getMaximumSupportedAssetCount()": FunctionFragment;
    "isValidAsset(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAssetPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetType",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaximumSupportedAssetCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidAsset",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAssetPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaximumSupportedAssetCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidAsset",
    data: BytesLike
  ): Result;

  events: {};
}

export class IHasAssetInfo extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IHasAssetInfoInterface;

  functions: {
    getAssetPrice(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAssetType(asset: string, overrides?: CallOverrides): Promise<[number]>;

    getMaximumSupportedAssetCount(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isValidAsset(asset: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  getAssetPrice(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

  getAssetType(asset: string, overrides?: CallOverrides): Promise<number>;

  getMaximumSupportedAssetCount(overrides?: CallOverrides): Promise<BigNumber>;

  isValidAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    getAssetPrice(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    getAssetType(asset: string, overrides?: CallOverrides): Promise<number>;

    getMaximumSupportedAssetCount(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getAssetPrice(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    getAssetType(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumSupportedAssetCount(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidAsset(asset: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAssetPrice(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAssetType(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaximumSupportedAssetCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
