/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IPoolPerformanceInterface extends ethers.utils.Interface {
  functions: {
    "adjustInternalValueFactor(uint256,uint256)": FunctionFragment;
    "changeAssetBalance(address,uint256,uint256)": FunctionFragment;
    "getBalancesSnapshot(address,tuple[])": FunctionFragment;
    "hasExternalBalances(address)": FunctionFragment;
    "initializePool()": FunctionFragment;
    "recordExternalValue(address)": FunctionFragment;
    "resetInternalValueFactor()": FunctionFragment;
    "updateInternalBalances()": FunctionFragment;
    "updatedInternalBalancesByDiff(tuple[],uint256[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "adjustInternalValueFactor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeAssetBalance",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalancesSnapshot",
    values: [string, { asset: string; isDeposit: boolean }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "hasExternalBalances",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initializePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordExternalValue",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "resetInternalValueFactor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateInternalBalances",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatedInternalBalancesByDiff",
    values: [
      { asset: string; isDeposit: boolean }[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "adjustInternalValueFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeAssetBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalancesSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasExternalBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordExternalValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetInternalValueFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateInternalBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatedInternalBalancesByDiff",
    data: BytesLike
  ): Result;

  events: {};
}

export class IPoolPerformance extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPoolPerformanceInterface;

  functions: {
    adjustInternalValueFactor(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeAssetBalance(
      asset: string,
      plusAmount: BigNumberish,
      minusAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getBalancesSnapshot(
      poolManagerAddress: string,
      supportedAssets: { asset: string; isDeposit: boolean }[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { supportedAssetBalances: BigNumber[] }>;

    hasExternalBalances(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initializePool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    recordExternalValue(
      poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    resetInternalValueFactor(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateInternalBalances(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updatedInternalBalancesByDiff(
      supportedAssets: { asset: string; isDeposit: boolean }[],
      beforeSupportedAssetBalances: BigNumberish[],
      afterSupportedAssetBalances: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  adjustInternalValueFactor(
    a: BigNumberish,
    b: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeAssetBalance(
    asset: string,
    plusAmount: BigNumberish,
    minusAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getBalancesSnapshot(
    poolManagerAddress: string,
    supportedAssets: { asset: string; isDeposit: boolean }[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  hasExternalBalances(
    poolAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initializePool(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  recordExternalValue(
    poolAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  resetInternalValueFactor(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateInternalBalances(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updatedInternalBalancesByDiff(
    supportedAssets: { asset: string; isDeposit: boolean }[],
    beforeSupportedAssetBalances: BigNumberish[],
    afterSupportedAssetBalances: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    adjustInternalValueFactor(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    changeAssetBalance(
      asset: string,
      plusAmount: BigNumberish,
      minusAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getBalancesSnapshot(
      poolManagerAddress: string,
      supportedAssets: { asset: string; isDeposit: boolean }[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    hasExternalBalances(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initializePool(overrides?: CallOverrides): Promise<void>;

    recordExternalValue(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    resetInternalValueFactor(overrides?: CallOverrides): Promise<void>;

    updateInternalBalances(overrides?: CallOverrides): Promise<void>;

    updatedInternalBalancesByDiff(
      supportedAssets: { asset: string; isDeposit: boolean }[],
      beforeSupportedAssetBalances: BigNumberish[],
      afterSupportedAssetBalances: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    adjustInternalValueFactor(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeAssetBalance(
      asset: string,
      plusAmount: BigNumberish,
      minusAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getBalancesSnapshot(
      poolManagerAddress: string,
      supportedAssets: { asset: string; isDeposit: boolean }[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasExternalBalances(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializePool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    recordExternalValue(
      poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    resetInternalValueFactor(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateInternalBalances(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updatedInternalBalancesByDiff(
      supportedAssets: { asset: string; isDeposit: boolean }[],
      beforeSupportedAssetBalances: BigNumberish[],
      afterSupportedAssetBalances: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    adjustInternalValueFactor(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeAssetBalance(
      asset: string,
      plusAmount: BigNumberish,
      minusAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getBalancesSnapshot(
      poolManagerAddress: string,
      supportedAssets: { asset: string; isDeposit: boolean }[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasExternalBalances(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializePool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    recordExternalValue(
      poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    resetInternalValueFactor(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateInternalBalances(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updatedInternalBalancesByDiff(
      supportedAssets: { asset: string; isDeposit: boolean }[],
      beforeSupportedAssetBalances: BigNumberish[],
      afterSupportedAssetBalances: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
