/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IPoolManagerLogicV24Interface extends ethers.utils.Interface {
  functions: {
    "assetValue(address,uint256)": FunctionFragment;
    "factory()": FunctionFragment;
    "getManagerFee()": FunctionFragment;
    "isDepositAsset(address)": FunctionFragment;
    "poolLogic()": FunctionFragment;
    "setPoolLogic(address)": FunctionFragment;
    "totalFundValue()": FunctionFragment;
    "validateAsset(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "assetValue",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getManagerFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isDepositAsset",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "poolLogic", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setPoolLogic",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFundValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateAsset",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "assetValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getManagerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDepositAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolLogic", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPoolLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFundValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateAsset",
    data: BytesLike
  ): Result;

  events: {};
}

export class IPoolManagerLogicV24 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPoolManagerLogicV24Interface;

  functions: {
    "assetValue(address,uint256)"(
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "assetValue(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    getManagerFee(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

    isDepositAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    poolLogic(overrides?: CallOverrides): Promise<[string]>;

    setPoolLogic(
      fundAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalFundValue(overrides?: CallOverrides): Promise<[BigNumber]>;

    validateAsset(asset: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  "assetValue(address,uint256)"(
    asset: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "assetValue(address)"(
    asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  factory(overrides?: CallOverrides): Promise<string>;

  getManagerFee(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

  isDepositAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;

  poolLogic(overrides?: CallOverrides): Promise<string>;

  setPoolLogic(
    fundAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalFundValue(overrides?: CallOverrides): Promise<BigNumber>;

  validateAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    "assetValue(address,uint256)"(
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "assetValue(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<string>;

    getManagerFee(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

    isDepositAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;

    poolLogic(overrides?: CallOverrides): Promise<string>;

    setPoolLogic(
      fundAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    totalFundValue(overrides?: CallOverrides): Promise<BigNumber>;

    validateAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    "assetValue(address,uint256)"(
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "assetValue(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    getManagerFee(overrides?: CallOverrides): Promise<BigNumber>;

    isDepositAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolLogic(overrides?: CallOverrides): Promise<BigNumber>;

    setPoolLogic(
      fundAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalFundValue(overrides?: CallOverrides): Promise<BigNumber>;

    validateAsset(asset: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    "assetValue(address,uint256)"(
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "assetValue(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getManagerFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isDepositAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolLogic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setPoolLogic(
      fundAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalFundValue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    validateAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
