/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ManagedV24Interface extends ethers.utils.Interface {
  functions: {
    "addMember(address)": FunctionFragment;
    "addMembers(address[])": FunctionFragment;
    "changeManager(address,string)": FunctionFragment;
    "getMembers()": FunctionFragment;
    "isMemberAllowed(address)": FunctionFragment;
    "manager()": FunctionFragment;
    "managerName()": FunctionFragment;
    "numberOfMembers()": FunctionFragment;
    "removeMember(address)": FunctionFragment;
    "removeMembers(address[])": FunctionFragment;
    "removeTrader()": FunctionFragment;
    "setTrader(address)": FunctionFragment;
    "trader()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addMember", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addMembers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "changeManager",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMembers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isMemberAllowed",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "managerName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfMembers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMembers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTrader",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setTrader", values: [string]): string;
  encodeFunctionData(functionFragment: "trader", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addMembers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMembers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isMemberAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "managerName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTrader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTrader", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trader", data: BytesLike): Result;

  events: {
    "ManagerUpdated(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ManagerUpdated"): EventFragment;
}

export type ManagerUpdatedEvent = TypedEvent<
  [string, string] & { newManager: string; newManagerName: string }
>;

export class ManagedV24 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ManagedV24Interface;

  functions: {
    addMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeManager(
      newManager: string,
      newManagerName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getMembers(overrides?: CallOverrides): Promise<[string[]]>;

    isMemberAllowed(
      member: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    manager(overrides?: CallOverrides): Promise<[string]>;

    managerName(overrides?: CallOverrides): Promise<[string]>;

    numberOfMembers(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeTrader(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTrader(
      newTrader: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    trader(overrides?: CallOverrides): Promise<[string]>;
  };

  addMember(
    member: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addMembers(
    members: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeManager(
    newManager: string,
    newManagerName: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getMembers(overrides?: CallOverrides): Promise<string[]>;

  isMemberAllowed(member: string, overrides?: CallOverrides): Promise<boolean>;

  manager(overrides?: CallOverrides): Promise<string>;

  managerName(overrides?: CallOverrides): Promise<string>;

  numberOfMembers(overrides?: CallOverrides): Promise<BigNumber>;

  removeMember(
    member: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeMembers(
    members: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeTrader(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTrader(
    newTrader: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  trader(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addMember(member: string, overrides?: CallOverrides): Promise<void>;

    addMembers(members: string[], overrides?: CallOverrides): Promise<void>;

    changeManager(
      newManager: string,
      newManagerName: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getMembers(overrides?: CallOverrides): Promise<string[]>;

    isMemberAllowed(
      member: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    manager(overrides?: CallOverrides): Promise<string>;

    managerName(overrides?: CallOverrides): Promise<string>;

    numberOfMembers(overrides?: CallOverrides): Promise<BigNumber>;

    removeMember(member: string, overrides?: CallOverrides): Promise<void>;

    removeMembers(members: string[], overrides?: CallOverrides): Promise<void>;

    removeTrader(overrides?: CallOverrides): Promise<void>;

    setTrader(newTrader: string, overrides?: CallOverrides): Promise<void>;

    trader(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ManagerUpdated(address,string)"(
      newManager?: null,
      newManagerName?: null
    ): TypedEventFilter<
      [string, string],
      { newManager: string; newManagerName: string }
    >;

    ManagerUpdated(
      newManager?: null,
      newManagerName?: null
    ): TypedEventFilter<
      [string, string],
      { newManager: string; newManagerName: string }
    >;
  };

  estimateGas: {
    addMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeManager(
      newManager: string,
      newManagerName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getMembers(overrides?: CallOverrides): Promise<BigNumber>;

    isMemberAllowed(
      member: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    managerName(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfMembers(overrides?: CallOverrides): Promise<BigNumber>;

    removeMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeTrader(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTrader(
      newTrader: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    trader(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeManager(
      newManager: string,
      newManagerName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getMembers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isMemberAllowed(
      member: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    managerName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numberOfMembers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeTrader(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTrader(
      newTrader: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    trader(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
