/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PoolPerformanceInterface extends ethers.utils.Interface {
  functions: {
    "DENOMINATOR()": FunctionFragment;
    "adjustInternalValueFactor(uint256,uint256)": FunctionFragment;
    "changeAssetBalance(address,uint256,uint256)": FunctionFragment;
    "enable()": FunctionFragment;
    "enabled()": FunctionFragment;
    "hasExternalBalances(address)": FunctionFragment;
    "initialize()": FunctionFragment;
    "initializePool()": FunctionFragment;
    "internalBalancesMap(address,address)": FunctionFragment;
    "internalValueFactor(address)": FunctionFragment;
    "internalValueFactorMap(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "poolInitialized(address)": FunctionFragment;
    "realtimeInternalValueFactor(address)": FunctionFragment;
    "recordExternalValue(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "resetInternalValueFactor()": FunctionFragment;
    "setInternalValueFactor(address,uint256)": FunctionFragment;
    "tokenPrice(address)": FunctionFragment;
    "tokenPriceAdjustedForPerformance(address)": FunctionFragment;
    "tokenPriceWithoutManagerFee(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateInternalBalances()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adjustInternalValueFactor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeAssetBalance",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "enable", values?: undefined): string;
  encodeFunctionData(functionFragment: "enabled", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasExternalBalances",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "internalBalancesMap",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "internalValueFactor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "internalValueFactorMap",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolInitialized",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "realtimeInternalValueFactor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordExternalValue",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resetInternalValueFactor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setInternalValueFactor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tokenPrice", values: [string]): string;
  encodeFunctionData(
    functionFragment: "tokenPriceAdjustedForPerformance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenPriceWithoutManagerFee",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateInternalBalances",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adjustInternalValueFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeAssetBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enabled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasExternalBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "internalBalancesMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "internalValueFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "internalValueFactorMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "realtimeInternalValueFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordExternalValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetInternalValueFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInternalValueFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenPriceAdjustedForPerformance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenPriceWithoutManagerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateInternalBalances",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class PoolPerformance extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PoolPerformanceInterface;

  functions: {
    DENOMINATOR(overrides?: CallOverrides): Promise<[BigNumber]>;

    adjustInternalValueFactor(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeAssetBalance(
      asset: string,
      plusAmount: BigNumberish,
      minusAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enable(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enabled(overrides?: CallOverrides): Promise<[boolean]>;

    hasExternalBalances(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializePool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    internalBalancesMap(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    internalValueFactor(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    internalValueFactorMap(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    poolInitialized(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    realtimeInternalValueFactor(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    recordExternalValue(
      poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    resetInternalValueFactor(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setInternalValueFactor(
      poolAddress: string,
      newInternalValueFactor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenPrice(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenPriceAdjustedForPerformance(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenPriceWithoutManagerFee(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateInternalBalances(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

  adjustInternalValueFactor(
    a: BigNumberish,
    b: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeAssetBalance(
    asset: string,
    plusAmount: BigNumberish,
    minusAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enable(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enabled(overrides?: CallOverrides): Promise<boolean>;

  hasExternalBalances(
    poolAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializePool(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  internalBalancesMap(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  internalValueFactor(
    poolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  internalValueFactorMap(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  poolInitialized(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  realtimeInternalValueFactor(
    poolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  recordExternalValue(
    poolAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  resetInternalValueFactor(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setInternalValueFactor(
    poolAddress: string,
    newInternalValueFactor: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenPrice(
    poolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenPriceAdjustedForPerformance(
    poolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenPriceWithoutManagerFee(
    poolAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateInternalBalances(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

    adjustInternalValueFactor(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    changeAssetBalance(
      asset: string,
      plusAmount: BigNumberish,
      minusAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    enable(overrides?: CallOverrides): Promise<void>;

    enabled(overrides?: CallOverrides): Promise<boolean>;

    hasExternalBalances(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(overrides?: CallOverrides): Promise<void>;

    initializePool(overrides?: CallOverrides): Promise<void>;

    internalBalancesMap(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    internalValueFactor(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    internalValueFactorMap(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    poolInitialized(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    realtimeInternalValueFactor(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recordExternalValue(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    resetInternalValueFactor(overrides?: CallOverrides): Promise<void>;

    setInternalValueFactor(
      poolAddress: string,
      newInternalValueFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenPrice(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenPriceAdjustedForPerformance(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenPriceWithoutManagerFee(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateInternalBalances(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

    adjustInternalValueFactor(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeAssetBalance(
      asset: string,
      plusAmount: BigNumberish,
      minusAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enable(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enabled(overrides?: CallOverrides): Promise<BigNumber>;

    hasExternalBalances(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializePool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    internalBalancesMap(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    internalValueFactor(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    internalValueFactorMap(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    poolInitialized(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    realtimeInternalValueFactor(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recordExternalValue(
      poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    resetInternalValueFactor(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setInternalValueFactor(
      poolAddress: string,
      newInternalValueFactor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenPrice(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenPriceAdjustedForPerformance(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenPriceWithoutManagerFee(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateInternalBalances(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DENOMINATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    adjustInternalValueFactor(
      a: BigNumberish,
      b: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeAssetBalance(
      asset: string,
      plusAmount: BigNumberish,
      minusAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enable(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hasExternalBalances(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializePool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    internalBalancesMap(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    internalValueFactor(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    internalValueFactorMap(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolInitialized(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    realtimeInternalValueFactor(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recordExternalValue(
      poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    resetInternalValueFactor(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setInternalValueFactor(
      poolAddress: string,
      newInternalValueFactor: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenPrice(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenPriceAdjustedForPerformance(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenPriceWithoutManagerFee(
      poolAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateInternalBalances(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
