/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PoolManagerLogicInterface extends ethers.utils.Interface {
  functions: {
    "addMember(address)": FunctionFragment;
    "addMembers(address[])": FunctionFragment;
    "announceManagerFeeIncrease(uint256)": FunctionFragment;
    "announcedFeeIncreaseNumerator()": FunctionFragment;
    "announcedFeeIncreaseTimestamp()": FunctionFragment;
    "assetBalance(address)": FunctionFragment;
    "assetDecimal(address)": FunctionFragment;
    "assetPosition(address)": FunctionFragment;
    "assetValue(address,uint256)": FunctionFragment;
    "changeAssets(tuple[],address[])": FunctionFragment;
    "changeManager(address,string)": FunctionFragment;
    "commitManagerFeeIncrease()": FunctionFragment;
    "factory()": FunctionFragment;
    "getDepositAssets()": FunctionFragment;
    "getFundComposition()": FunctionFragment;
    "getManagerFee()": FunctionFragment;
    "getManagerFeeIncreaseInfo()": FunctionFragment;
    "getMaximumManagerFee()": FunctionFragment;
    "getMaximumManagerFeeChange()": FunctionFragment;
    "getMembers()": FunctionFragment;
    "getSupportedAssets()": FunctionFragment;
    "initialize(address,address,string,address,uint256,tuple[])": FunctionFragment;
    "isDepositAsset(address)": FunctionFragment;
    "isMemberAllowed(address)": FunctionFragment;
    "isSupportedAsset(address)": FunctionFragment;
    "manager()": FunctionFragment;
    "managerFeeNumerator()": FunctionFragment;
    "managerName()": FunctionFragment;
    "numberOfMembers()": FunctionFragment;
    "poolLogic()": FunctionFragment;
    "removeMember(address)": FunctionFragment;
    "removeMembers(address[])": FunctionFragment;
    "removeTrader()": FunctionFragment;
    "renounceManagerFeeIncrease()": FunctionFragment;
    "setManagerFeeNumerator(uint256)": FunctionFragment;
    "setPoolLogic(address)": FunctionFragment;
    "setTrader(address)": FunctionFragment;
    "supportedAssets(uint256)": FunctionFragment;
    "totalFundValue()": FunctionFragment;
    "trader()": FunctionFragment;
    "validateAsset(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addMember", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addMembers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "announceManagerFeeIncrease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "announcedFeeIncreaseNumerator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "announcedFeeIncreaseTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "assetDecimal",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "assetPosition",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "assetValue",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeAssets",
    values: [{ asset: string; isDeposit: boolean }[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "changeManager",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "commitManagerFeeIncrease",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDepositAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFundComposition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getManagerFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getManagerFeeIncreaseInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaximumManagerFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaximumManagerFeeChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMembers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      { asset: string; isDeposit: boolean }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isDepositAsset",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isMemberAllowed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupportedAsset",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "managerFeeNumerator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "managerName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfMembers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "poolLogic", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMembers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTrader",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceManagerFeeIncrease",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setManagerFeeNumerator",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolLogic",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setTrader", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supportedAssets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFundValue",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "trader", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validateAsset",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addMembers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "announceManagerFeeIncrease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "announcedFeeIncreaseNumerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "announcedFeeIncreaseTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetDecimal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitManagerFeeIncrease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDepositAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFundComposition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getManagerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getManagerFeeIncreaseInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaximumManagerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaximumManagerFeeChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMembers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDepositAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMemberAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSupportedAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "managerFeeNumerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "managerName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolLogic", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTrader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceManagerFeeIncrease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setManagerFeeNumerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTrader", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFundValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trader", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateAsset",
    data: BytesLike
  ): Result;

  events: {
    "AssetAdded(address,address,address,bool)": EventFragment;
    "AssetRemoved(address,address,address)": EventFragment;
    "ManagerFeeIncreaseAnnounced(uint256,uint256)": EventFragment;
    "ManagerFeeIncreaseRenounced()": EventFragment;
    "ManagerFeeSet(address,address,uint256,uint256)": EventFragment;
    "ManagerUpdated(address,string)": EventFragment;
    "PoolLogicSet(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssetAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssetRemoved"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ManagerFeeIncreaseAnnounced"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ManagerFeeIncreaseRenounced"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ManagerFeeSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ManagerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolLogicSet"): EventFragment;
}

export type AssetAddedEvent = TypedEvent<
  [string, string, string, boolean] & {
    fundAddress: string;
    manager: string;
    asset: string;
    isDeposit: boolean;
  }
>;

export type AssetRemovedEvent = TypedEvent<
  [string, string, string] & {
    fundAddress: string;
    manager: string;
    asset: string;
  }
>;

export type ManagerFeeIncreaseAnnouncedEvent = TypedEvent<
  [BigNumber, BigNumber] & {
    newNumerator: BigNumber;
    announcedFeeActivationTime: BigNumber;
  }
>;

export type ManagerFeeIncreaseRenouncedEvent = TypedEvent<[] & {}>;

export type ManagerFeeSetEvent = TypedEvent<
  [string, string, BigNumber, BigNumber] & {
    fundAddress: string;
    manager: string;
    numerator: BigNumber;
    denominator: BigNumber;
  }
>;

export type ManagerUpdatedEvent = TypedEvent<
  [string, string] & { newManager: string; newManagerName: string }
>;

export type PoolLogicSetEvent = TypedEvent<
  [string, string] & { poolLogic: string; from: string }
>;

export class PoolManagerLogic extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PoolManagerLogicInterface;

  functions: {
    addMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    announceManagerFeeIncrease(
      numerator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    announcedFeeIncreaseNumerator(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    announcedFeeIncreaseTimestamp(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    assetBalance(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    assetDecimal(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { decimal: BigNumber }>;

    assetPosition(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "assetValue(address,uint256)"(
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    "assetValue(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    changeAssets(
      _addAssets: { asset: string; isDeposit: boolean }[],
      _removeAssets: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeManager(
      newManager: string,
      newManagerName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    commitManagerFeeIncrease(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    getDepositAssets(overrides?: CallOverrides): Promise<[string[]]>;

    getFundComposition(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, boolean] & { asset: string; isDeposit: boolean })[],
        BigNumber[],
        BigNumber[]
      ] & {
        assets: ([string, boolean] & { asset: string; isDeposit: boolean })[];
        balances: BigNumber[];
        rates: BigNumber[];
      }
    >;

    getManagerFee(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

    getManagerFeeIncreaseInfo(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getMaximumManagerFee(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
    >;

    getMaximumManagerFeeChange(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { change: BigNumber }>;

    getMembers(
      overrides?: CallOverrides
    ): Promise<[string[]] & { members: string[] }>;

    getSupportedAssets(
      overrides?: CallOverrides
    ): Promise<[([string, boolean] & { asset: string; isDeposit: boolean })[]]>;

    initialize(
      _factory: string,
      _manager: string,
      _managerName: string,
      _poolLogic: string,
      _managerFeeNumerator: BigNumberish,
      _supportedAssets: { asset: string; isDeposit: boolean }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isDepositAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isMemberAllowed(
      member: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isSupportedAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    manager(overrides?: CallOverrides): Promise<[string]>;

    managerFeeNumerator(overrides?: CallOverrides): Promise<[BigNumber]>;

    managerName(overrides?: CallOverrides): Promise<[string]>;

    numberOfMembers(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _numberOfMembers: BigNumber }>;

    poolLogic(overrides?: CallOverrides): Promise<[string]>;

    removeMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeTrader(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceManagerFeeIncrease(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setManagerFeeNumerator(
      numerator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPoolLogic(
      _poolLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTrader(
      newTrader: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportedAssets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, boolean] & { asset: string; isDeposit: boolean }>;

    totalFundValue(overrides?: CallOverrides): Promise<[BigNumber]>;

    trader(overrides?: CallOverrides): Promise<[string]>;

    validateAsset(asset: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  addMember(
    member: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addMembers(
    members: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  announceManagerFeeIncrease(
    numerator: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  announcedFeeIncreaseNumerator(overrides?: CallOverrides): Promise<BigNumber>;

  announcedFeeIncreaseTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  assetBalance(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

  assetDecimal(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

  assetPosition(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "assetValue(address,uint256)"(
    asset: string,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "assetValue(address)"(
    asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  changeAssets(
    _addAssets: { asset: string; isDeposit: boolean }[],
    _removeAssets: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeManager(
    newManager: string,
    newManagerName: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  commitManagerFeeIncrease(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  getDepositAssets(overrides?: CallOverrides): Promise<string[]>;

  getFundComposition(
    overrides?: CallOverrides
  ): Promise<
    [
      ([string, boolean] & { asset: string; isDeposit: boolean })[],
      BigNumber[],
      BigNumber[]
    ] & {
      assets: ([string, boolean] & { asset: string; isDeposit: boolean })[];
      balances: BigNumber[];
      rates: BigNumber[];
    }
  >;

  getManagerFee(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

  getManagerFeeIncreaseInfo(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getMaximumManagerFee(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
  >;

  getMaximumManagerFeeChange(overrides?: CallOverrides): Promise<BigNumber>;

  getMembers(overrides?: CallOverrides): Promise<string[]>;

  getSupportedAssets(
    overrides?: CallOverrides
  ): Promise<([string, boolean] & { asset: string; isDeposit: boolean })[]>;

  initialize(
    _factory: string,
    _manager: string,
    _managerName: string,
    _poolLogic: string,
    _managerFeeNumerator: BigNumberish,
    _supportedAssets: { asset: string; isDeposit: boolean }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isDepositAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;

  isMemberAllowed(member: string, overrides?: CallOverrides): Promise<boolean>;

  isSupportedAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;

  manager(overrides?: CallOverrides): Promise<string>;

  managerFeeNumerator(overrides?: CallOverrides): Promise<BigNumber>;

  managerName(overrides?: CallOverrides): Promise<string>;

  numberOfMembers(overrides?: CallOverrides): Promise<BigNumber>;

  poolLogic(overrides?: CallOverrides): Promise<string>;

  removeMember(
    member: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeMembers(
    members: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeTrader(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceManagerFeeIncrease(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setManagerFeeNumerator(
    numerator: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPoolLogic(
    _poolLogic: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTrader(
    newTrader: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportedAssets(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, boolean] & { asset: string; isDeposit: boolean }>;

  totalFundValue(overrides?: CallOverrides): Promise<BigNumber>;

  trader(overrides?: CallOverrides): Promise<string>;

  validateAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    addMember(member: string, overrides?: CallOverrides): Promise<void>;

    addMembers(members: string[], overrides?: CallOverrides): Promise<void>;

    announceManagerFeeIncrease(
      numerator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    announcedFeeIncreaseNumerator(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    announcedFeeIncreaseTimestamp(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    assetBalance(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    assetDecimal(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    assetPosition(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "assetValue(address,uint256)"(
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "assetValue(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeAssets(
      _addAssets: { asset: string; isDeposit: boolean }[],
      _removeAssets: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    changeManager(
      newManager: string,
      newManagerName: string,
      overrides?: CallOverrides
    ): Promise<void>;

    commitManagerFeeIncrease(overrides?: CallOverrides): Promise<void>;

    factory(overrides?: CallOverrides): Promise<string>;

    getDepositAssets(overrides?: CallOverrides): Promise<string[]>;

    getFundComposition(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, boolean] & { asset: string; isDeposit: boolean })[],
        BigNumber[],
        BigNumber[]
      ] & {
        assets: ([string, boolean] & { asset: string; isDeposit: boolean })[];
        balances: BigNumber[];
        rates: BigNumber[];
      }
    >;

    getManagerFee(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

    getManagerFeeIncreaseInfo(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getMaximumManagerFee(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
    >;

    getMaximumManagerFeeChange(overrides?: CallOverrides): Promise<BigNumber>;

    getMembers(overrides?: CallOverrides): Promise<string[]>;

    getSupportedAssets(
      overrides?: CallOverrides
    ): Promise<([string, boolean] & { asset: string; isDeposit: boolean })[]>;

    initialize(
      _factory: string,
      _manager: string,
      _managerName: string,
      _poolLogic: string,
      _managerFeeNumerator: BigNumberish,
      _supportedAssets: { asset: string; isDeposit: boolean }[],
      overrides?: CallOverrides
    ): Promise<void>;

    isDepositAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;

    isMemberAllowed(
      member: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isSupportedAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    manager(overrides?: CallOverrides): Promise<string>;

    managerFeeNumerator(overrides?: CallOverrides): Promise<BigNumber>;

    managerName(overrides?: CallOverrides): Promise<string>;

    numberOfMembers(overrides?: CallOverrides): Promise<BigNumber>;

    poolLogic(overrides?: CallOverrides): Promise<string>;

    removeMember(member: string, overrides?: CallOverrides): Promise<void>;

    removeMembers(members: string[], overrides?: CallOverrides): Promise<void>;

    removeTrader(overrides?: CallOverrides): Promise<void>;

    renounceManagerFeeIncrease(overrides?: CallOverrides): Promise<void>;

    setManagerFeeNumerator(
      numerator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPoolLogic(
      _poolLogic: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setTrader(newTrader: string, overrides?: CallOverrides): Promise<void>;

    supportedAssets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, boolean] & { asset: string; isDeposit: boolean }>;

    totalFundValue(overrides?: CallOverrides): Promise<BigNumber>;

    trader(overrides?: CallOverrides): Promise<string>;

    validateAsset(asset: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "AssetAdded(address,address,address,bool)"(
      fundAddress?: string | null,
      manager?: null,
      asset?: null,
      isDeposit?: null
    ): TypedEventFilter<
      [string, string, string, boolean],
      {
        fundAddress: string;
        manager: string;
        asset: string;
        isDeposit: boolean;
      }
    >;

    AssetAdded(
      fundAddress?: string | null,
      manager?: null,
      asset?: null,
      isDeposit?: null
    ): TypedEventFilter<
      [string, string, string, boolean],
      {
        fundAddress: string;
        manager: string;
        asset: string;
        isDeposit: boolean;
      }
    >;

    "AssetRemoved(address,address,address)"(
      fundAddress?: null,
      manager?: null,
      asset?: null
    ): TypedEventFilter<
      [string, string, string],
      { fundAddress: string; manager: string; asset: string }
    >;

    AssetRemoved(
      fundAddress?: null,
      manager?: null,
      asset?: null
    ): TypedEventFilter<
      [string, string, string],
      { fundAddress: string; manager: string; asset: string }
    >;

    "ManagerFeeIncreaseAnnounced(uint256,uint256)"(
      newNumerator?: null,
      announcedFeeActivationTime?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { newNumerator: BigNumber; announcedFeeActivationTime: BigNumber }
    >;

    ManagerFeeIncreaseAnnounced(
      newNumerator?: null,
      announcedFeeActivationTime?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { newNumerator: BigNumber; announcedFeeActivationTime: BigNumber }
    >;

    "ManagerFeeIncreaseRenounced()"(): TypedEventFilter<[], {}>;

    ManagerFeeIncreaseRenounced(): TypedEventFilter<[], {}>;

    "ManagerFeeSet(address,address,uint256,uint256)"(
      fundAddress?: null,
      manager?: null,
      numerator?: null,
      denominator?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        fundAddress: string;
        manager: string;
        numerator: BigNumber;
        denominator: BigNumber;
      }
    >;

    ManagerFeeSet(
      fundAddress?: null,
      manager?: null,
      numerator?: null,
      denominator?: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      {
        fundAddress: string;
        manager: string;
        numerator: BigNumber;
        denominator: BigNumber;
      }
    >;

    "ManagerUpdated(address,string)"(
      newManager?: null,
      newManagerName?: null
    ): TypedEventFilter<
      [string, string],
      { newManager: string; newManagerName: string }
    >;

    ManagerUpdated(
      newManager?: null,
      newManagerName?: null
    ): TypedEventFilter<
      [string, string],
      { newManager: string; newManagerName: string }
    >;

    "PoolLogicSet(address,address)"(
      poolLogic?: null,
      from?: null
    ): TypedEventFilter<[string, string], { poolLogic: string; from: string }>;

    PoolLogicSet(
      poolLogic?: null,
      from?: null
    ): TypedEventFilter<[string, string], { poolLogic: string; from: string }>;
  };

  estimateGas: {
    addMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    announceManagerFeeIncrease(
      numerator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    announcedFeeIncreaseNumerator(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    announcedFeeIncreaseTimestamp(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    assetBalance(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    assetDecimal(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    assetPosition(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "assetValue(address,uint256)"(
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "assetValue(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeAssets(
      _addAssets: { asset: string; isDeposit: boolean }[],
      _removeAssets: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeManager(
      newManager: string,
      newManagerName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    commitManagerFeeIncrease(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    getDepositAssets(overrides?: CallOverrides): Promise<BigNumber>;

    getFundComposition(overrides?: CallOverrides): Promise<BigNumber>;

    getManagerFee(overrides?: CallOverrides): Promise<BigNumber>;

    getManagerFeeIncreaseInfo(overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumManagerFee(overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumManagerFeeChange(overrides?: CallOverrides): Promise<BigNumber>;

    getMembers(overrides?: CallOverrides): Promise<BigNumber>;

    getSupportedAssets(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _factory: string,
      _manager: string,
      _managerName: string,
      _poolLogic: string,
      _managerFeeNumerator: BigNumberish,
      _supportedAssets: { asset: string; isDeposit: boolean }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isDepositAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isMemberAllowed(
      member: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSupportedAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    managerFeeNumerator(overrides?: CallOverrides): Promise<BigNumber>;

    managerName(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfMembers(overrides?: CallOverrides): Promise<BigNumber>;

    poolLogic(overrides?: CallOverrides): Promise<BigNumber>;

    removeMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeTrader(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceManagerFeeIncrease(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setManagerFeeNumerator(
      numerator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPoolLogic(
      _poolLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTrader(
      newTrader: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportedAssets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalFundValue(overrides?: CallOverrides): Promise<BigNumber>;

    trader(overrides?: CallOverrides): Promise<BigNumber>;

    validateAsset(asset: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    announceManagerFeeIncrease(
      numerator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    announcedFeeIncreaseNumerator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    announcedFeeIncreaseTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    assetBalance(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    assetDecimal(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    assetPosition(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "assetValue(address,uint256)"(
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "assetValue(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    changeAssets(
      _addAssets: { asset: string; isDeposit: boolean }[],
      _removeAssets: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeManager(
      newManager: string,
      newManagerName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    commitManagerFeeIncrease(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDepositAssets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFundComposition(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getManagerFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getManagerFeeIncreaseInfo(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaximumManagerFee(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaximumManagerFeeChange(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMembers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSupportedAssets(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _factory: string,
      _manager: string,
      _managerName: string,
      _poolLogic: string,
      _managerFeeNumerator: BigNumberish,
      _supportedAssets: { asset: string; isDeposit: boolean }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isDepositAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMemberAllowed(
      member: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSupportedAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    managerFeeNumerator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    managerName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numberOfMembers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolLogic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeMember(
      member: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeMembers(
      members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeTrader(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceManagerFeeIncrease(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setManagerFeeNumerator(
      numerator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPoolLogic(
      _poolLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTrader(
      newTrader: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportedAssets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalFundValue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    trader(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    validateAsset(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
