/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface UniswapV3SwapGuardInterface extends ethers.utils.Interface {
  functions: {
    "convert32toAddress(bytes32)": FunctionFragment;
    "getArrayIndex(bytes,uint8,uint8)": FunctionFragment;
    "getArrayLast(bytes,uint8)": FunctionFragment;
    "getArrayLength(bytes,uint8)": FunctionFragment;
    "getBytes(bytes,uint8,uint256)": FunctionFragment;
    "getInput(bytes,uint8)": FunctionFragment;
    "getMethod(bytes)": FunctionFragment;
    "getParams(bytes)": FunctionFragment;
    "read32(bytes,uint256,uint256)": FunctionFragment;
    "read4left(bytes,uint256)": FunctionFragment;
    "txGuard(address,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "convert32toAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getArrayIndex",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getArrayLast",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getArrayLength",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBytes",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInput",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMethod",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getParams",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "read32",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "read4left",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "txGuard",
    values: [string, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "convert32toAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArrayIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArrayLast",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArrayLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getInput", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMethod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getParams", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "read32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "read4left", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "txGuard", data: BytesLike): Result;

  events: {
    "ExchangeFrom(address,address,uint256,address,uint256)": EventFragment;
    "ExchangeTo(address,address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExchangeFrom"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExchangeTo"): EventFragment;
}

export type ExchangeFromEvent = TypedEvent<
  [string, string, BigNumber, string, BigNumber] & {
    fundAddress: string;
    sourceAsset: string;
    sourceAmount: BigNumber;
    dstAsset: string;
    time: BigNumber;
  }
>;

export type ExchangeToEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber] & {
    fundAddress: string;
    sourceAsset: string;
    dstAsset: string;
    dstAmount: BigNumber;
    time: BigNumber;
  }
>;

export class UniswapV3SwapGuard extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UniswapV3SwapGuardInterface;

  functions: {
    convert32toAddress(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { o: string }>;

    getArrayIndex(
      data: BytesLike,
      inputNum: BigNumberish,
      arrayIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getArrayLast(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getArrayLength(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getBytes(
      data: BytesLike,
      inputNum: BigNumberish,
      offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getInput(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMethod(data: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getParams(data: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    read32(
      data: BytesLike,
      offset: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { o: string }>;

    read4left(
      data: BytesLike,
      offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { o: string }>;

    txGuard(
      _poolManagerLogic: string,
      arg1: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  convert32toAddress(
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getArrayIndex(
    data: BytesLike,
    inputNum: BigNumberish,
    arrayIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getArrayLast(
    data: BytesLike,
    inputNum: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getArrayLength(
    data: BytesLike,
    inputNum: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getBytes(
    data: BytesLike,
    inputNum: BigNumberish,
    offset: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getInput(
    data: BytesLike,
    inputNum: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getMethod(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  getParams(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  read32(
    data: BytesLike,
    offset: BigNumberish,
    length: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  read4left(
    data: BytesLike,
    offset: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  txGuard(
    _poolManagerLogic: string,
    arg1: string,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    convert32toAddress(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getArrayIndex(
      data: BytesLike,
      inputNum: BigNumberish,
      arrayIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getArrayLast(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getArrayLength(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBytes(
      data: BytesLike,
      inputNum: BigNumberish,
      offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getInput(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getMethod(data: BytesLike, overrides?: CallOverrides): Promise<string>;

    getParams(data: BytesLike, overrides?: CallOverrides): Promise<string>;

    read32(
      data: BytesLike,
      offset: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    read4left(
      data: BytesLike,
      offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    txGuard(
      _poolManagerLogic: string,
      arg1: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number, boolean] & { txType: number }>;
  };

  filters: {
    "ExchangeFrom(address,address,uint256,address,uint256)"(
      fundAddress?: null,
      sourceAsset?: null,
      sourceAmount?: null,
      dstAsset?: null,
      time?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, BigNumber],
      {
        fundAddress: string;
        sourceAsset: string;
        sourceAmount: BigNumber;
        dstAsset: string;
        time: BigNumber;
      }
    >;

    ExchangeFrom(
      fundAddress?: null,
      sourceAsset?: null,
      sourceAmount?: null,
      dstAsset?: null,
      time?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, BigNumber],
      {
        fundAddress: string;
        sourceAsset: string;
        sourceAmount: BigNumber;
        dstAsset: string;
        time: BigNumber;
      }
    >;

    "ExchangeTo(address,address,address,uint256,uint256)"(
      fundAddress?: null,
      sourceAsset?: null,
      dstAsset?: null,
      dstAmount?: null,
      time?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber],
      {
        fundAddress: string;
        sourceAsset: string;
        dstAsset: string;
        dstAmount: BigNumber;
        time: BigNumber;
      }
    >;

    ExchangeTo(
      fundAddress?: null,
      sourceAsset?: null,
      dstAsset?: null,
      dstAmount?: null,
      time?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber],
      {
        fundAddress: string;
        sourceAsset: string;
        dstAsset: string;
        dstAmount: BigNumber;
        time: BigNumber;
      }
    >;
  };

  estimateGas: {
    convert32toAddress(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getArrayIndex(
      data: BytesLike,
      inputNum: BigNumberish,
      arrayIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getArrayLast(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getArrayLength(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBytes(
      data: BytesLike,
      inputNum: BigNumberish,
      offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInput(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMethod(data: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getParams(data: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    read32(
      data: BytesLike,
      offset: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    read4left(
      data: BytesLike,
      offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    txGuard(
      _poolManagerLogic: string,
      arg1: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    convert32toAddress(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getArrayIndex(
      data: BytesLike,
      inputNum: BigNumberish,
      arrayIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getArrayLast(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getArrayLength(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBytes(
      data: BytesLike,
      inputNum: BigNumberish,
      offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInput(
      data: BytesLike,
      inputNum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMethod(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getParams(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    read32(
      data: BytesLike,
      offset: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    read4left(
      data: BytesLike,
      offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    txGuard(
      _poolManagerLogic: string,
      arg1: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
