/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  DHedgePoolAggregator,
  DHedgePoolAggregatorInterface,
} from "../DHedgePoolAggregator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_poolLogic",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "latestRoundData",
    outputs: [
      {
        internalType: "uint80",
        name: "",
        type: "uint80",
      },
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint80",
        name: "",
        type: "uint80",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "poolLogic",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516102d43803806102d48339818101604052602081101561003357600080fd5b50516001600160a01b038116610090576040805162461bcd60e51b815260206004820152601e60248201527f5f706f6f6c4c6f67696320616464726573732063616e6e6f7420626520300000604482015290519081900360640190fd5b600080546001600160a01b039092166001600160a01b0319909216919091179055610214806100c06000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806339b81fd91461003b578063feaf968c1461005f575b600080fd5b6100436100b1565b604080516001600160a01b039092168252519081900360200190f35b6100676100c0565b604051808669ffffffffffffffffffff1681526020018581526020018481526020018381526020018269ffffffffffffffffffff1681526020019550505050505060405180910390f35b6000546001600160a01b031681565b60008060008060008060008054906101000a90046001600160a01b03166001600160a01b0316637ff9b5966040518163ffffffff1660e01b815260040160206040518083038186803b15801561011557600080fd5b505afa158015610129573d6000803e3d6000fd5b505050506040513d602081101561013f57600080fd5b505190506000811561015f5761015a826402540be400610177565b610162565b60005b60009890975088965042955086945092505050565b60008082116101cd576040805162461bcd60e51b815260206004820152601a60248201527f536166654d6174683a206469766973696f6e206279207a65726f000000000000604482015290519081900360640190fd5b8183816101d657fe5b04939250505056fea2646970667358221220399945c56ca4a1b6032b607bc7256f19f07665ebddf997a6ea985c90cc2e482e64736f6c63430007060033";

export class DHedgePoolAggregator__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    _poolLogic: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DHedgePoolAggregator> {
    return super.deploy(
      _poolLogic,
      overrides || {}
    ) as Promise<DHedgePoolAggregator>;
  }
  getDeployTransaction(
    _poolLogic: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_poolLogic, overrides || {});
  }
  attach(address: string): DHedgePoolAggregator {
    return super.attach(address) as DHedgePoolAggregator;
  }
  connect(signer: Signer): DHedgePoolAggregator__factory {
    return super.connect(signer) as DHedgePoolAggregator__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DHedgePoolAggregatorInterface {
    return new utils.Interface(_abi) as DHedgePoolAggregatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DHedgePoolAggregator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DHedgePoolAggregator;
  }
}
