/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAaveProtocolDataProvider,
  IAaveProtocolDataProviderInterface,
} from "../IAaveProtocolDataProvider";

const _abi = [
  {
    inputs: [],
    name: "ADDRESSES_PROVIDER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getReserveTokensAddresses",
    outputs: [
      {
        internalType: "address",
        name: "aTokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "stableDebtTokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "variableDebtTokenAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAaveProtocolDataProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveProtocolDataProviderInterface {
    return new utils.Interface(_abi) as IAaveProtocolDataProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAaveProtocolDataProvider {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAaveProtocolDataProvider;
  }
}
