/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAaveLendingPoolAssetGuard,
  IAaveLendingPoolAssetGuardInterface,
} from "../IAaveLendingPoolAssetGuard";

const _abi = [
  {
    inputs: [],
    name: "aaveLendingPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "portion",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "repayAssets",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "repayAmounts",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "premiums",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "interestRateModes",
        type: "uint256[]",
      },
    ],
    name: "flashloanProcessing",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "txData",
            type: "bytes",
          },
        ],
        internalType: "struct IAssetGuard.MultiTransaction[]",
        name: "transactions",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAaveLendingPoolAssetGuard__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveLendingPoolAssetGuardInterface {
    return new utils.Interface(_abi) as IAaveLendingPoolAssetGuardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAaveLendingPoolAssetGuard {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAaveLendingPoolAssetGuard;
  }
}
