/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IGuard, IGuardInterface } from "../IGuard";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "fundAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sourceAsset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "sourceAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "dstAsset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "ExchangeFrom",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "fundAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sourceAsset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "dstAsset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "dstAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "ExchangeTo",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "poolManagerLogic",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "txGuard",
    outputs: [
      {
        internalType: "uint16",
        name: "txType",
        type: "uint16",
      },
      {
        internalType: "bool",
        name: "isPublic",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGuard__factory {
  static readonly abi = _abi;
  static createInterface(): IGuardInterface {
    return new utils.Interface(_abi) as IGuardInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IGuard {
    return new Contract(address, _abi, signerOrProvider) as IGuard;
  }
}
