/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHasOwnableV24,
  IHasOwnableV24Interface,
} from "../IHasOwnableV24";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IHasOwnableV24__factory {
  static readonly abi = _abi;
  static createInterface(): IHasOwnableV24Interface {
    return new utils.Interface(_abi) as IHasOwnableV24Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasOwnableV24 {
    return new Contract(address, _abi, signerOrProvider) as IHasOwnableV24;
  }
}
