/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHasDaoInfoV24,
  IHasDaoInfoV24Interface,
} from "../IHasDaoInfoV24";

const _abi = [
  {
    inputs: [],
    name: "daoAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDaoFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IHasDaoInfoV24__factory {
  static readonly abi = _abi;
  static createInterface(): IHasDaoInfoV24Interface {
    return new utils.Interface(_abi) as IHasDaoInfoV24Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasDaoInfoV24 {
    return new Contract(address, _abi, signerOrProvider) as IHasDaoInfoV24;
  }
}
