/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHasFeeInfoV24,
  IHasFeeInfoV24Interface,
} from "../IHasFeeInfoV24";

const _abi = [
  {
    inputs: [],
    name: "getExitCooldown",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMaximumManagerFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "managerFeeNumeratorChangeDelay",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maximumManagerFeeNumeratorChange",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IHasFeeInfoV24__factory {
  static readonly abi = _abi;
  static createInterface(): IHasFeeInfoV24Interface {
    return new utils.Interface(_abi) as IHasFeeInfoV24Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasFeeInfoV24 {
    return new Contract(address, _abi, signerOrProvider) as IHasFeeInfoV24;
  }
}
