/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHasSupportedAsset,
  IHasSupportedAssetInterface,
} from "../IHasSupportedAsset";

const _abi = [
  {
    inputs: [],
    name: "getSupportedAssets",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isDeposit",
            type: "bool",
          },
        ],
        internalType: "struct IHasSupportedAsset.Asset[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "isSupportedAsset",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IHasSupportedAsset__factory {
  static readonly abi = _abi;
  static createInterface(): IHasSupportedAssetInterface {
    return new utils.Interface(_abi) as IHasSupportedAssetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasSupportedAsset {
    return new Contract(address, _abi, signerOrProvider) as IHasSupportedAsset;
  }
}
