/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHasProtocolDaoInfoV24,
  IHasProtocolDaoInfoV24Interface,
} from "../IHasProtocolDaoInfoV24";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IHasProtocolDaoInfoV24__factory {
  static readonly abi = _abi;
  static createInterface(): IHasProtocolDaoInfoV24Interface {
    return new utils.Interface(_abi) as IHasProtocolDaoInfoV24Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasProtocolDaoInfoV24 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IHasProtocolDaoInfoV24;
  }
}
