/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHasPoolPerformance,
  IHasPoolPerformanceInterface,
} from "../IHasPoolPerformance";

const _abi = [
  {
    inputs: [],
    name: "poolPerformanceAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IHasPoolPerformance__factory {
  static readonly abi = _abi;
  static createInterface(): IHasPoolPerformanceInterface {
    return new utils.Interface(_abi) as IHasPoolPerformanceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasPoolPerformance {
    return new Contract(address, _abi, signerOrProvider) as IHasPoolPerformance;
  }
}
