/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHasSupportedAssetV24,
  IHasSupportedAssetV24Interface,
} from "../IHasSupportedAssetV24";

const _abi = [
  {
    inputs: [],
    name: "getSupportedAssets",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isDeposit",
            type: "bool",
          },
        ],
        internalType: "struct IHasSupportedAssetV24.Asset[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "isSupportedAsset",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IHasSupportedAssetV24__factory {
  static readonly abi = _abi;
  static createInterface(): IHasSupportedAssetV24Interface {
    return new utils.Interface(_abi) as IHasSupportedAssetV24Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasSupportedAssetV24 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IHasSupportedAssetV24;
  }
}
