/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IHasPausable, IHasPausableInterface } from "../IHasPausable";

const _abi = [
  {
    inputs: [],
    name: "isPaused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IHasPausable__factory {
  static readonly abi = _abi;
  static createInterface(): IHasPausableInterface {
    return new utils.Interface(_abi) as IHasPausableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasPausable {
    return new Contract(address, _abi, signerOrProvider) as IHasPausable;
  }
}
