/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IStakingRewardsFactory,
  IStakingRewardsFactoryInterface,
} from "../IStakingRewardsFactory";

const _abi = [
  {
    inputs: [],
    name: "rewardsToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "stakingToken",
        type: "address",
      },
    ],
    name: "stakingRewardsInfoByStakingToken",
    outputs: [
      {
        internalType: "address",
        name: "stakingRewards",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IStakingRewardsFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IStakingRewardsFactoryInterface {
    return new utils.Interface(_abi) as IStakingRewardsFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStakingRewardsFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IStakingRewardsFactory;
  }
}
