/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISystemStatus, ISystemStatusInterface } from "../ISystemStatus";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "currencyKey",
        type: "bytes32",
      },
    ],
    name: "requireSynthActive",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
];

export class ISystemStatus__factory {
  static readonly abi = _abi;
  static createInterface(): ISystemStatusInterface {
    return new utils.Interface(_abi) as ISystemStatusInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISystemStatus {
    return new Contract(address, _abi, signerOrProvider) as ISystemStatus;
  }
}
